//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace home.manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Str {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Str() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("home.manager.Resources.Str", typeof(Str).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string account_msg_ChangePassword {
            get {
                return ResourceManager.GetString("account_msg_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string account_msg_ConfirmPassword {
            get {
                return ResourceManager.GetString("account_msg_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string account_msg_NewPassword {
            get {
                return ResourceManager.GetString("account_msg_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string account_msg_OldPassword {
            get {
                return ResourceManager.GetString("account_msg_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string action_Edit {
            get {
                return ResourceManager.GetString("action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string action_Remove {
            get {
                return ResourceManager.GetString("action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btn_OK {
            get {
                return ResourceManager.GetString("btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit &amp;&amp; New.
        /// </summary>
        public static string btn_SubmitNew {
            get {
                return ResourceManager.GetString("btn_SubmitNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string chart_select_AllTime {
            get {
                return ResourceManager.GetString("chart_select_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string chart_select_Months {
            get {
                return ResourceManager.GetString("chart_select_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Months.
        /// </summary>
        public static string chart_select_Months12 {
            get {
                return ResourceManager.GetString("chart_select_Months12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        public static string chart_select_Months3 {
            get {
                return ResourceManager.GetString("chart_select_Months3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        public static string chart_select_Months6 {
            get {
                return ResourceManager.GetString("chart_select_Months6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string chart_select_Years {
            get {
                return ResourceManager.GetString("chart_select_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Years.
        /// </summary>
        public static string chart_select_Years2 {
            get {
                return ResourceManager.GetString("chart_select_Years2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Years.
        /// </summary>
        public static string chart_select_Years5 {
            get {
                return ResourceManager.GetString("chart_select_Years5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come in.
        /// </summary>
        public static string ComeIn {
            get {
                return ResourceManager.GetString("ComeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string grid_Actions {
            get {
                return ResourceManager.GetString("grid_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string grid_Added {
            get {
                return ResourceManager.GetString("grid_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string grid_All {
            get {
                return ResourceManager.GetString("grid_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string grid_Amount {
            get {
                return ResourceManager.GetString("grid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string grid_Category {
            get {
                return ResourceManager.GetString("grid_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string grid_Contacts {
            get {
                return ResourceManager.GetString("grid_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string grid_Date {
            get {
                return ResourceManager.GetString("grid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string grid_Description {
            get {
                return ResourceManager.GetString("grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string grid_FileName {
            get {
                return ResourceManager.GetString("grid_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string grid_Item {
            get {
                return ResourceManager.GetString("grid_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string grid_Length {
            get {
                return ResourceManager.GetString("grid_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string grid_Link {
            get {
                return ResourceManager.GetString("grid_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string grid_Name {
            get {
                return ResourceManager.GetString("grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string grid_Owner {
            get {
                return ResourceManager.GetString("grid_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent.
        /// </summary>
        public static string grid_Spent {
            get {
                return ResourceManager.GetString("grid_Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string grid_Title {
            get {
                return ResourceManager.GetString("grid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string grid_Type {
            get {
                return ResourceManager.GetString("grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Manager.
        /// </summary>
        public static string HomeManager {
            get {
                return ResourceManager.GetString("HomeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Statistic Charts.
        /// </summary>
        public static string msg_MainStatisticCharts {
            get {
                return ResourceManager.GetString("msg_MainStatisticCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent:.
        /// </summary>
        public static string msg_Spent {
            get {
                return ResourceManager.GetString("msg_Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent Money (per month).
        /// </summary>
        public static string msg_SpentMoneyPerMonth {
            get {
                return ResourceManager.GetString("msg_SpentMoneyPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Table.
        /// </summary>
        public static string msg_SummaryTable {
            get {
                return ResourceManager.GetString("msg_SummaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .. to think about and to change something ...
        /// </summary>
        public static string msg_ToThinkAbout {
            get {
                return ResourceManager.GetString("msg_ToThinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Documents.
        /// </summary>
        public static string nav_adddoc {
            get {
                return ResourceManager.GetString("nav_adddoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string nav_addnew {
            get {
                return ResourceManager.GetString("nav_addnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string nav_category {
            get {
                return ResourceManager.GetString("nav_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Farg/Drop is not supported for this browser.
        /// </summary>
        public static string nav_docerror {
            get {
                return ResourceManager.GetString("nav_docerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Images or PDFs files here.
        /// </summary>
        public static string nav_dropdoc {
            get {
                return ResourceManager.GetString("nav_dropdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        public static string nav_owner {
            get {
                return ResourceManager.GetString("nav_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search ....
        /// </summary>
        public static string nav_search {
            get {
                return ResourceManager.GetString("nav_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Category.
        /// </summary>
        public static string nav_specifyCategory {
            get {
                return ResourceManager.GetString("nav_specifyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Ownership.
        /// </summary>
        public static string nav_specifyOwnership {
            get {
                return ResourceManager.GetString("nav_specifyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string select_all {
            get {
                return ResourceManager.GetString("select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Items.
        /// </summary>
        public static string setting_local_MergeItems {
            get {
                return ResourceManager.GetString("setting_local_MergeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select a new category.
        /// </summary>
        public static string setting_local_PleaseSelectNewCategory {
            get {
                return ResourceManager.GetString("setting_local_PleaseSelectNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be moved to.
        /// </summary>
        public static string setting_local_WillBeMovedTo {
            get {
                return ResourceManager.GetString("setting_local_WillBeMovedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Categories.
        /// </summary>
        public static string Setting_tabName_ContactCategories {
            get {
                return ResourceManager.GetString("Setting_tabName_ContactCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Title.
        /// </summary>
        public static string Setting_tabName_EditTitle {
            get {
                return ResourceManager.GetString("Setting_tabName_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Categories.
        /// </summary>
        public static string Setting_tabName_ExpenseCategories {
            get {
                return ResourceManager.GetString("Setting_tabName_ExpenseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Categories.
        /// </summary>
        public static string Setting_tabName_NoteCategories {
            get {
                return ResourceManager.GetString("Setting_tabName_NoteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Categories.
        /// </summary>
        public static string Setting_tabName_SecurityCategories {
            get {
                return ResourceManager.GetString("Setting_tabName_SecurityCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contact.
        /// </summary>
        public static string ttl_AddContact {
            get {
                return ResourceManager.GetString("ttl_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string ttl_AddItem {
            get {
                return ResourceManager.GetString("ttl_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new expense.
        /// </summary>
        public static string ttl_AddNewExpense {
            get {
                return ResourceManager.GetString("ttl_AddNewExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete contact?.
        /// </summary>
        public static string ttl_DeleteContact {
            get {
                return ResourceManager.GetString("ttl_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document ?.
        /// </summary>
        public static string ttl_DeleteDocument {
            get {
                return ResourceManager.GetString("ttl_DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete expense ?.
        /// </summary>
        public static string ttl_DeleteExpense {
            get {
                return ResourceManager.GetString("ttl_DeleteExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item?.
        /// </summary>
        public static string ttl_DeleteItem {
            get {
                return ResourceManager.GetString("ttl_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contact.
        /// </summary>
        public static string ttl_EditContact {
            get {
                return ResourceManager.GetString("ttl_EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expense.
        /// </summary>
        public static string ttl_EditExpense {
            get {
                return ResourceManager.GetString("ttl_EditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string ttl_EditItem {
            get {
                return ResourceManager.GetString("ttl_EditItem", resourceCulture);
            }
        }
    }
}
